
package org.simon.zhao.webService.com.demo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TokenPayService", targetNamespace = "http://oaas.creditcard.cmbchina.com", wsdlLocation = "file:/D:/webservice/TokenPay.wsdl")
public class TokenPayService
    extends Service
{

    private final static URL TOKENPAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOKENPAYSERVICE_EXCEPTION;
    private final static QName TOKENPAYSERVICE_QNAME = new QName("http://oaas.creditcard.cmbchina.com", "TokenPayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/webservice/TokenPay.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOKENPAYSERVICE_WSDL_LOCATION = url;
        TOKENPAYSERVICE_EXCEPTION = e;
    }

    public TokenPayService() {
        super(__getWsdlLocation(), TOKENPAYSERVICE_QNAME);
    }

    public TokenPayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENPAYSERVICE_QNAME, features);
    }

    public TokenPayService(URL wsdlLocation) {
        super(wsdlLocation, TOKENPAYSERVICE_QNAME);
    }

    public TokenPayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENPAYSERVICE_QNAME, features);
    }

    public TokenPayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenPayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenPay
     */
    @WebEndpoint(name = "TokenPay")
    public TokenPay getTokenPay() {
        return super.getPort(new QName("http://oaas.creditcard.cmbchina.com", "TokenPay"), TokenPay.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenPay
     */
    @WebEndpoint(name = "TokenPay")
    public TokenPay getTokenPay(WebServiceFeature... features) {
        return super.getPort(new QName("http://oaas.creditcard.cmbchina.com", "TokenPay"), TokenPay.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENPAYSERVICE_EXCEPTION!= null) {
            throw TOKENPAYSERVICE_EXCEPTION;
        }
        return TOKENPAYSERVICE_WSDL_LOCATION;
    }

}
